#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no-install commitlint --edit

#[
#  'build',
#  'chore',
#  'ci',
#  'docs',
#  'feat',
#  'fix',
#  'perf',
#  'refactor',
#  'revert',
#  'style',
#  'test'
#];

#echo "fix: some message" # passes
